# Generated by Django 2.2.3 on 2019-07-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.CharField(choices=[('True', 'Completed'), ('False', 'Uncompleted')], default='False', max_length=2)),
                ('task', models.CharField(max_length=250)),
                ('due_date', models.DateField(default='2019-07-03')),
            ],
        ),
    ]
