# Generated by Django 2.2.3 on 2019-07-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2019-07-03'),
        ),
    ]
