# Generated by Django 2.2.3 on 2019-07-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('completed', models.CharField(choices=[('True', 'Completed'), ('False', 'Uncompleted')], default='False', max_length=2)),
                ('id', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=250)),
                ('due_date', models.DateField(default='2019-07-02')),
            ],
        ),
    ]
